name: Docker Image CI
on:
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo chmod a+rw -R /var/lib/docker
    - id: cache-docker
      uses: actions/cache@v1
      with:
        path: /var/lib/docker
        key: cache-var-lib-docker-${{ hashFiles('Dockerfile') }}
    - run: docker build . -t thing
    - run: sudo chmod a+rw -R /var/lib/docker
      if: always()
